version: '3'

volumes:
  mongo-data:
    driver: local
  minio-data:
    driver: local

services:
  frontend:
    build: ./frontend
    image: nginx-react:v1
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: ./backend
    image: nest-be:v1
    restart: unless-stopped
    environment:
      - PORT=5005
      - MONGO_URL=mongodb://admin:pass123@mongodb:27017
      - MONGO_DB_NAME=test2-db
      - NODE_ENV=dev
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESSKEY=minio
      - MINIO_SECRETKEY=minio123
      - MINIO_BUCKET=files
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /minio/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
