version: '3'

services:
  frontend:
    build: ./frontend
    image: nginx-react:v1
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: ./backend
    image: nest-be:v1
    restart: unless-stopped
    # ports:
    #   - 5005:5005
    environment:
      - PORT=5005
      - MONGO_URL=mongodb://admin:pass123@mongodb:27017
      - MONGO_DB_NAME=test2-db
      - NODE_ENV=dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local